// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BLE_SOC_CONFIG__
#define __BLE_SOC_CONFIG__




// Top level macros
#define SILABS_AF_DEVICE_NAME "bleDemoSoc-hr-server_2"


// Generated plugin macros

// Use this macro to check if Advertisement plugin is included
#define SILABS_AF_PLUGIN_ADVERTISEMENT
// User options for plugin Advertisement
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MIN1 20
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MAX1 30
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TIME1 30
#define ADV_GENERAL_DISCOVERABLE 1
#define ADV_LIMITED_DISCOVERABLE 2
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TYPE1 ADV_GENERAL_DISCOVERABLE
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MIN2 1000
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_INT_MAX2 2500
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TIME2 120
#define ADV_GENERAL_DISCOVERABLE 1
#define ADV_LIMITED_DISCOVERABLE 2
#define SILABS_AF_PLUGIN_ADVERTISEMENT_ADV_TYPE2 ADV_LIMITED_DISCOVERABLE

// Use this macro to check if Bluetooth Smart Demo Application plugin is included
#define SILABS_AF_PLUGIN_APP

// Use this macro to check if Bluetooth Smart Demo Application Hardware Abstraction plugin is included
#define SILABS_AF_PLUGIN_APP_HW

// Use this macro to check if Connection plugin is included
#define SILABS_AF_PLUGIN_CONNECTION
// User options for plugin Connection
#define SILABS_AF_PLUGIN_CONNECTION_CON_PAIRING
#define SILABS_AF_PLUGIN_CONNECTION_CON_BONDING

// Use this macro to check if Device Information plugin is included
#define SILABS_AF_PLUGIN_DEVICE_INFO
// User options for plugin Device Information
#define SILABS_AF_PLUGIN_DEVICE_INFO_MAN_NAME_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_MAN_NAME_STRING "Silicon Labs"
#define SILABS_AF_PLUGIN_DEVICE_INFO_MAN_NAME_STRING_LENGTH (12)
#define SILABS_AF_PLUGIN_DEVICE_INFO_MOD_NUM_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_MOD_NUM_STRING "1.0"
#define SILABS_AF_PLUGIN_DEVICE_INFO_MOD_NUM_STRING_LENGTH (3)
#define SILABS_AF_PLUGIN_DEVICE_INFO_SER_NUM_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_SER_NUM_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_SER_NUM_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_HW_REV_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_HW_REV_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_HW_REV_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_FW_REV_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_FW_REV_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_FW_REV_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_SW_REV_STRING_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_SW_REV_STRING "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_SW_REV_STRING_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_SYS_ID_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_SYS_ID "ffffffffffffffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_SYS_ID_LENGTH (16)
#define SILABS_AF_PLUGIN_DEVICE_INFO_REG_CERT_D_L_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_REG_CERT_D_L "ffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_REG_CERT_D_L_LENGTH (4)
#define SILABS_AF_PLUGIN_DEVICE_INFO_PNP_ID_EN
#define SILABS_AF_PLUGIN_DEVICE_INFO_PNP_ID "01ffffffffffff"
#define SILABS_AF_PLUGIN_DEVICE_INFO_PNP_ID_LENGTH (14)

// Use this macro to check if GAP plugin is included
#define SILABS_AF_PLUGIN_GAP
// User options for plugin GAP
#define GAP_UNKNOWN 0
#define GAP_GENERIC_THERMOMETER 3
#define GAP_HR_SENSOR 4003
#define GAP_KEYBOARD C103
#define GAP_CSC_SENSOR 8504
#define GAP_CSP 8404
#define SILABS_AF_PLUGIN_GAP_DEV_APPEARANCE GAP_HR_SENSOR

// Use this macro to check if Heart Rate plugin is included
#define SILABS_AF_PLUGIN_HR
// User options for plugin Heart Rate
#define HR_UINT8 0
#define HR_UINT16 1
#define SILABS_AF_PLUGIN_HR_HR_VALUE_FORMAT HR_UINT8
#define HR_SENS_NO_SUP 0
#define HR_SENS_SUP_NOT_DET 1
#define HR_SENS_SUP_DET 2
#define SILABS_AF_PLUGIN_HR_HR_SENSOR_CONTACT HR_SENS_NO_SUP
#define SILABS_AF_PLUGIN_HR_ENERGY_EXP_SUP
#define SILABS_AF_PLUGIN_HR_RR_INT_SUP
#define SILABS_AF_PLUGIN_HR_HR_SENSOR_LOCATION_SUP
#define OTHER 0
#define HR_CHEST 1
#define HR_WRIST 2
#define HR_FINGER 3
#define HR_HAND 4
#define HR_EAR_LOBE 5
#define HR_FOOT 6
#define SILABS_AF_PLUGIN_HR_HR_SENSOR_LOCATION OTHER

// Use this macro to check if Idle/Sleep plugin is included
#define SILABS_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define SILABS_AF_PLUGIN_IDLE_SLEEP_MINIMUM_DURATION_MS 5

// Use this macro to check if Bluetooth Smart Platform plugin is included
#define SILABS_AF_PLUGIN_PLATFORM

// Use this macro to check if Bluetooth Smart Platform Hardware Abstraction plugin is included
#define SILABS_AF_PLUGIN_PLATFORM_HW

// Use this macro to check if Packet Trace Interface plugin is included
#define SILABS_AF_PLUGIN_PTI
// User options for plugin Packet Trace Interface
#define SILABS_AF_PLUGIN_PTI_BAUD 1600000
#define SILABS_AF_PLUGIN_PTI_D_OUT_LOC 6
#define GPIOPORTA 0
#define GPIOPORTB 1
#define GPIOPORTC 2
#define GPIOPORTD 3
#define GPIOPORTE 4
#define GPIOPORTF 5
#define GPIOPORTG 6
#define GPIOPORTH 7
#define SILABS_AF_PLUGIN_PTI_DOUT_PORT GPIOPORTB
#define SILABS_AF_PLUGIN_PTI_DOUT_PIN 12
#define SILABS_AF_PLUGIN_PTI_DFRAME_LOC 6
#define GPIOPORTA 0
#define GPIOPORTB 1
#define GPIOPORTC 2
#define GPIOPORTD 3
#define GPIOPORTE 4
#define GPIOPORTF 5
#define GPIOPORTG 6
#define GPIOPORTH 7
#define SILABS_AF_PLUGIN_PTI_DFRAME_PORT GPIOPORTB
#define SILABS_AF_PLUGIN_PTI_DFRAME_PIN 13


// Generated API headers

// API app_hw from Bluetooth Smart Demo Application Hardware Abstraction plugin
#define SILABS_AF_API_APP_HW "../../../../../SiliconLabs/BluetoothSmartSDK/1.0.4.0-GA/sdk/plugins/app_hw/app_hw.h"


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32BG1B232F256GM48

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY B

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE B

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 232

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 256K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 48

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32BG1B232F256GM48

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY B

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE B

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 232

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 256K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 48

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4300AREVA02



#endif // __BLE_SOC_CONFIG__
